# Generated by Django 5.0.6 on 2024-06-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['blocker'], name='authenticat_blocker_a8d3b5_idx'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['blocked'], name='authenticat_blocked_fed7d4_idx'),
        ),
    ]
