# Generated by Django 5.0.6 on 2024-07-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_block_authenticat_blocker_a8d3b5_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='images/avatar.jpeg', null=True, upload_to='images/'),
        ),
    ]
