# Generated by Django 5.0.6 on 2024-07-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_remove_postcount_post_delete_post_delete_postcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hide_avatar',
            field=models.BooleanField(default=False),
        ),
    ]
